name: Pacman

on: 
 workflow_dispatch: 
  branches: 
   -main 

jobs: 
  deploy: 
   name: deploy
   runs-on : ubuntu-latest
   steps: 
    - name : connecting to ssh vm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 47.254.215.8
        username: syakir
        password: Syakir1234
        port: 22
        script: |
         git clone https://github.com/mo-ake/pacman-deployment-automation
         cd pacman-deployment-automation
         sudo npm install
         sudo npm run start
         
         
   
        
