name : pacman

on: 
 workflow_dispatch:

jobs: 
    deploy: 
      runs-on: ubuntu-latest
      strategy: 
       matrix: 
        node_version: ["6.9.0 "]
        mongodb-version: ["3.4"]
      steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node_version }}

      - name: npm install, build and test
        run: |
         npm install
         npm run build --if-present
         npm test

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.9.0
        with: 
         mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      - run: npm test
        
