name: Pacman

on: 
 push: 
  branches: 
   -main 

jobs: 
  deploy: 
   name: deploy
   runs-on : ubuntu-latest
   steps: 
    - name : connecting to ssh vm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        
   
        
