name: pull

on: 
  push:
    branches:
    - main
    - release/*

jobs: 
  deploy: 
   name: deploy
   runs-on : ubuntu-latest
   steps: 
    - name : connecting to ssh vm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        port: ${{ secrets.port }}
        script: |
         cd pacman-deployment-automation
         git fetch origin main
         git pull
